services:
  db:
    image: postgres:15.8
    ports:
      - 5459:5432
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
    volumes:
      - pg_data_portfolio:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  pg_data_portfolio:
